import type { Metadata } from "next";
import { Fira_Sans_Condensed, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const firaSansCondensed = Fira_Sans_Condensed({
  variable: "--font-fira-sans-condensed",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-200 text-gray-900 dark:bg-slate-900">
      <body className={`${firaSansCondensed.variable} ${poppins.variable} antialiased font-[family-name:var(--font-poppins)] text-sm`}>
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
